export const DOCUMENT_ADD_TEXT = 'DOCUMENT_ADD_TEXT';
export const DOCUMENT_NEW_DIFF = 'DOCUMENT_NEW_DIFF';

export const DOCUMENT_RECEIVE_DIFFS_LOADING = 'DOCUMENT_RECEIVE_DIFFS_LOADING';
export const DOCUMENT_RECEIVE_DIFFS_ERROR = 'DOCUMENT_RECEIVE_DIFFS_ERROR';
export const DOCUMENT_RECEIVE_DIFFS_SUCCESS = 'DOCUMENT_RECEIVE_DIFFS_SUCCESS';
